export enum ErrorCode {
    HEXAGON_INVALID_SIZE          = 'HEXAGON_INVALID_SIZE',
    HEXAGON_ROTATION_OUT_OF_RANGE = 'HEXAGON_ROTATION_OUT_OF_RANGE',
    HEXAGON_INDEX_OUT_OF_RANGE    = 'HEXAGON_INDEX_OUT_OF_RANGE',

    HEXBOARD_OUT_OF_BOUNDS        = 'HEXBOARD_OUT_OF_BOUNDS',
    HEXBOARD_POSITION_OCCUPIED    = 'HEXBOARD_POSITION_OCCUPIED',
    HEXBOARD_NO_ADJACENT          = 'HEXBOARD_NO_ADJACENT',
    HEXBOARD_NEIGHBOR_CONFLICT    = 'HEXBOARD_NEIGHBOR_CONFLICT',

    NOT_FOUND                     = 'NOT_FOUND',
    PLAYER_NOT_FOUND              = 'PLAYER_NOT_FOUND',
    PLAYER_NOT_AUTHENTICATED      = 'PLAYER_NOT_AUTHENTICATED',
    INTERNAL_ERROR                = 'INTERNAL_ERROR',
}
